"use server";
import { revalidatePath } from "next/cache";
import { requireAdmin } from "@/features/auth/session";
import { deleteExperience, moveExperience, saveExperience } from "@/features/experience/service";
import { experienceFormSchema, experienceIdSchema, moveExperienceSchema, type ExperienceActionState } from "@/features/experience/validation";
function values(formData: FormData) { return { id: formData.get("id") || undefined, organization: formData.get("organization"), organizationUrl: formData.get("organizationUrl"), position: formData.get("position"), location: formData.get("location"), startDate: formData.get("startDate"), endDate: formData.get("endDate"), isCurrent: formData.get("isCurrent") === "on", descriptionMarkdown: formData.get("descriptionMarkdown") }; }
export async function saveExperienceAction(_state: ExperienceActionState, formData: FormData): Promise<ExperienceActionState> { await requireAdmin(); const parsed = experienceFormSchema.safeParse(values(formData)); if (!parsed.success) return { status: "error", message: "Review the experience fields.", fieldErrors: parsed.error.flatten().fieldErrors }; try { await saveExperience(parsed.data); revalidatePath("/admin/experience"); revalidatePath("/cv"); return { status: "success", message: parsed.data.id ? "Experience saved." : "Experience added." }; } catch (error) { console.error("Experience save failed.", error instanceof Error ? error.name : "UnknownError"); return { status: "error", message: "The experience record could not be saved." }; } }
export async function deleteExperienceAction(id: string) { await requireAdmin(); const parsed = experienceIdSchema.safeParse(id); if (!parsed.success) return; await deleteExperience(parsed.data); revalidatePath("/admin/experience"); revalidatePath("/cv"); }
export async function moveExperienceAction(id: string, direction: string) { await requireAdmin(); const parsed = moveExperienceSchema.safeParse({ id, direction }); if (!parsed.success) return; await moveExperience(parsed.data.id, parsed.data.direction); revalidatePath("/admin/experience"); revalidatePath("/cv"); }
