"use client";

import { ArrowDown, ArrowUp, ExternalLink, Plus, Trash2 } from "lucide-react";
import Link from "next/link";
import { useActionState, useState } from "react";

import { MarkdownEditor } from "@/components/markdown/markdown-editor";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { MediaField } from "@/features/media/media-field";
import type { MediaRecord } from "@/features/media/queries";
import { autosavePublicationAction, renderPublicationMarkdownPreviewAction, updatePublicationAction } from "@/features/publications/actions";
import { PdfField } from "@/features/publications/pdf-field";
import type { PublicationActionState, PublicationAuthorInput, PublicationFormInput, PublicationStatus } from "@/features/publications/validation";
import { FormField } from "@/features/profile/form-field";

interface Props { availableMedia: MediaRecord[]; initialPreviewHtml: string; initialPublication: PublicationFormInput; initialStatus: PublicationStatus }
interface AuthorRow extends PublicationAuthorInput { key: string }
export function PublicationEditorForm(props: Props) { const [state, action, pending] = useActionState(updatePublicationAction, {}); const publication = state.savedPublication ?? props.initialPublication; const status = state.savedStatus ?? props.initialStatus; return <PublicationFields {...props} action={action} key={JSON.stringify({ publication, status })} pending={pending} publication={publication} state={state} status={status} />; }
function PublicationFields({ action, availableMedia, initialPreviewHtml, pending, publication, state, status }: Omit<Props, "initialPublication" | "initialStatus"> & { action: (payload: FormData) => void; pending: boolean; publication: PublicationFormInput; state: PublicationActionState; status: PublicationStatus }) {
  const [markdown, setMarkdown] = useState(publication.contentMarkdown);
  const [authors, setAuthors] = useState<AuthorRow[]>(() => publication.authors.map((author, index) => ({ ...author, key: `${index}-${author.name}` })));
  function patchAuthor(index: number, patch: Partial<PublicationAuthorInput>) { setAuthors((current) => current.map((author, position) => position === index ? { ...author, ...patch } : author)); }
  function move(index: number, direction: -1 | 1) { setAuthors((current) => { const target = index + direction; if (target < 0 || target >= current.length) return current; const next = [...current]; [next[index], next[target]] = [next[target], next[index]]; return next; }); }
  const serializedAuthors = JSON.stringify(authors.map(({ name, profileUrl, isOwner }) => ({ name, profileUrl, isOwner })));
  return <form action={action} className="space-y-6"><input name="id" type="hidden" value={publication.id} /><input name="authors" type="hidden" value={serializedAuthors} /><textarea hidden name="contentMarkdown" readOnly value={markdown} />
    {state.message ? <div aria-live="polite" className={state.status === "success" ? "rounded-md border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800" : "rounded-md border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800"}>{state.message}</div> : null}
    <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div><span className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-500">CMS status</span><p className="mt-1 font-semibold capitalize">{status}</p></div><Link className="inline-flex items-center gap-2 text-sm font-semibold text-teal-800 underline underline-offset-4" href={`/preview/publications/${publication.id}`} target="_blank">Preview public layout <ExternalLink className="size-4" /></Link></div>
    <section className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-serif text-xl font-semibold">Publication details</h2><div className="mt-5 grid gap-5 sm:grid-cols-2"><FormField errors={state.fieldErrors?.title} htmlFor="title" label="Title"><Input defaultValue={publication.title} id="title" maxLength={300} name="title" required /></FormField><FormField errors={state.fieldErrors?.slug} htmlFor="slug" label="Slug"><Input defaultValue={publication.slug} id="slug" name="slug" required /></FormField><FormField errors={state.fieldErrors?.publicationType} htmlFor="publicationType" label="Type"><Select defaultValue={publication.publicationType} id="publicationType" name="publicationType">{["journal", "conference", "preprint", "thesis", "book", "chapter", "report", "other"].map((value) => <option key={value} value={value}>{value[0]?.toUpperCase()}{value.slice(1)}</option>)}</Select></FormField><FormField errors={state.fieldErrors?.publicationDate} htmlFor="publicationDate" label="Publication date"><Input defaultValue={publication.publicationDate ?? ""} id="publicationDate" name="publicationDate" type="date" /></FormField><FormField errors={state.fieldErrors?.venue} htmlFor="venue" label="Venue"><Input defaultValue={publication.venue ?? ""} id="venue" name="venue" /></FormField><FormField errors={state.fieldErrors?.publisher} htmlFor="publisher" label="Publisher"><Input defaultValue={publication.publisher ?? ""} id="publisher" name="publisher" /></FormField><div className="sm:col-span-2"><FormField errors={state.fieldErrors?.abstract} htmlFor="abstract" label="Abstract"><Textarea defaultValue={publication.abstract} id="abstract" maxLength={10000} name="abstract" rows={5} /></FormField></div><FormField errors={state.fieldErrors?.doi} htmlFor="doi" label="DOI"><Input defaultValue={publication.doi ?? ""} id="doi" name="doi" placeholder="10.1000/example" /></FormField><FormField errors={state.fieldErrors?.externalUrl} htmlFor="externalUrl" label="External URL"><Input defaultValue={publication.externalUrl ?? ""} id="externalUrl" name="externalUrl" type="url" /></FormField><label className="flex items-center gap-2 text-sm font-medium"><input className="size-4" defaultChecked={publication.isFeatured} name="isFeatured" type="checkbox" /> Featured publication</label><div className="sm:col-span-2"><PdfField initialId={publication.pdfMediaId} media={availableMedia} /></div></div></section>
    <section className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-serif text-xl font-semibold">Authors</h2><p className="mt-1 text-sm text-slate-500">Public presentation follows this order.</p></div><Button className="gap-2" onClick={() => setAuthors((current) => [...current, { key: `${Date.now()}-${current.length}`, name: "", profileUrl: null, isOwner: false }])} type="button"><Plus className="size-4" /> Add author</Button></div><div className="mt-5 space-y-4">{authors.map((author, index) => <div className="grid gap-3 rounded-lg border border-slate-200 p-4 sm:grid-cols-[1fr_1fr_auto]" key={author.key}><Input aria-label={`Author ${index + 1} name`} onChange={(event) => patchAuthor(index, { name: event.target.value })} placeholder="Author name" value={author.name} /><Input aria-label={`Author ${index + 1} profile URL`} onChange={(event) => patchAuthor(index, { profileUrl: event.target.value || null })} placeholder="https://…" type="url" value={author.profileUrl ?? ""} /><div className="flex items-center gap-1"><label className="mr-2 flex items-center gap-1 text-xs"><input checked={author.isOwner} onChange={(event) => patchAuthor(index, { isOwner: event.target.checked })} type="checkbox" /> Owner</label><Button aria-label={`Move ${author.name || `author ${index + 1}`} up`} className="bg-transparent px-2 text-slate-700 shadow-none hover:bg-slate-100" disabled={index === 0} onClick={() => move(index, -1)} type="button"><ArrowUp className="size-4" /></Button><Button aria-label={`Move ${author.name || `author ${index + 1}`} down`} className="bg-transparent px-2 text-slate-700 shadow-none hover:bg-slate-100" disabled={index === authors.length - 1} onClick={() => move(index, 1)} type="button"><ArrowDown className="size-4" /></Button><Button aria-label={`Delete ${author.name || `author ${index + 1}`}`} className="bg-transparent px-2 text-red-700 shadow-none hover:bg-red-50" onClick={() => setAuthors((current) => current.filter((_, position) => position !== index))} type="button"><Trash2 className="size-4" /></Button></div></div>)}</div>{state.fieldErrors?.authors?.map((error) => <p className="mt-2 text-sm text-red-700" key={error}>{error}</p>)}</section>
    <MarkdownEditor autosaveAction={autosavePublicationAction} contentId={publication.id} initialPreviewHtml={initialPreviewHtml} media={availableMedia} onChange={setMarkdown} previewAction={renderPublicationMarkdownPreviewAction} value={markdown} />
    <section className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-serif text-xl font-semibold">Search and sharing</h2><p className="mt-1 text-sm text-slate-500">Optional overrides; shared SEO helpers remain Milestone 11.</p><div className="mt-5 grid gap-5 sm:grid-cols-2"><FormField errors={state.fieldErrors?.seoTitle} htmlFor="seoTitle" label="SEO title"><Input defaultValue={publication.seoTitle ?? ""} id="seoTitle" name="seoTitle" /></FormField><FormField errors={state.fieldErrors?.seoDescription} htmlFor="seoDescription" label="SEO description"><Input defaultValue={publication.seoDescription ?? ""} id="seoDescription" name="seoDescription" /></FormField><FormField errors={state.fieldErrors?.canonicalUrl} htmlFor="canonicalUrl" label="Canonical URL"><Input defaultValue={publication.canonicalUrl ?? ""} id="canonicalUrl" name="canonicalUrl" type="url" /></FormField><MediaField description="Choose an uploaded image for social previews." initialId={publication.ogMediaId} initialMedia={availableMedia} label="Managed social image" name="ogMediaId" /><FormField errors={state.fieldErrors?.ogImageUrl} htmlFor="ogImageUrl" label="External social image URL"><Input defaultValue={publication.ogImageUrl ?? ""} id="ogImageUrl" name="ogImageUrl" type="url" /></FormField></div></section>
    <div className="flex flex-wrap justify-end gap-3">{status !== "draft" ? <Button className="border border-slate-300 bg-white text-slate-700 shadow-none hover:bg-slate-100" disabled={pending} name="intent" type="submit" value="draft">Move to draft</Button> : null}{status !== "archived" ? <Button className="border border-slate-300 bg-white text-slate-700 shadow-none hover:bg-slate-100" disabled={pending} name="intent" type="submit" value="archive">Archive</Button> : null}<Button className="border border-slate-300 bg-white text-slate-700 shadow-none hover:bg-slate-100" disabled={pending} name="intent" type="submit" value="save">Save changes</Button>{status !== "published" ? <Button disabled={pending} name="intent" type="submit" value="publish">Publish</Button> : null}</div>
  </form>;
}
