import { ExternalLink, FileText } from "lucide-react";

import { MarkdownContent } from "@/components/markdown/markdown-content";
import type { PublicationAuthorRecord } from "@/features/publications/queries";
import type { PublicationType } from "@/features/publications/validation";

function formatDate(value: string | null) { return value ? new Date(`${value}T00:00:00Z`).toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric", timeZone: "UTC" }) : null; }
export function PublicationPresentation({ abstract, authors, doi, externalUrl, html, pdfUrl, publicationDate, publicationType, publisher, title, venue }: { abstract: string; authors: PublicationAuthorRecord[]; doi: string | null; externalUrl: string | null; html: string; pdfUrl: string | null; publicationDate: string | null; publicationType: PublicationType; publisher: string | null; title: string; venue: string | null }) {
  return <article><header className="mb-8 border-b border-slate-200 pb-7"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--public-accent)]">{publicationType}</p><h1 className="mt-3 font-serif text-4xl font-semibold tracking-tight text-slate-950 sm:text-5xl">{title}</h1>{authors.length ? <p className="mt-4 leading-7 text-slate-700">{authors.map((author, index) => <span key={author.id}>{index ? ", " : ""}{author.profileUrl ? <a className={author.isOwner ? "font-semibold text-[var(--public-accent)] underline underline-offset-4" : "underline underline-offset-4"} href={author.profileUrl} rel="noopener noreferrer" target="_blank">{author.name}</a> : <span className={author.isOwner ? "font-semibold text-[var(--public-accent)]" : ""}>{author.name}</span>}</span>)}</p> : null}<p className="mt-3 text-sm text-slate-500">{[venue, publisher, formatDate(publicationDate)].filter(Boolean).join(" · ")}</p>{abstract ? <p className="mt-5 text-lg leading-8 text-slate-600">{abstract}</p> : null}<div className="mt-5 flex flex-wrap gap-4">{doi ? <a className="inline-flex items-center gap-1.5 font-semibold text-[var(--public-accent)] underline underline-offset-4" href={`https://doi.org/${doi}`} rel="noopener noreferrer" target="_blank">DOI <ExternalLink className="size-4" /><span className="sr-only"> (opens in a new tab)</span></a> : null}{externalUrl ? <a className="inline-flex items-center gap-1.5 font-semibold text-[var(--public-accent)] underline underline-offset-4" href={externalUrl} rel="noopener noreferrer" target="_blank">Publication site <ExternalLink className="size-4" /><span className="sr-only"> (opens in a new tab)</span></a> : null}{pdfUrl ? <a className="inline-flex items-center gap-1.5 font-semibold text-[var(--public-accent)] underline underline-offset-4" href={pdfUrl} rel="noopener noreferrer" target="_blank"><FileText className="size-4" /> PDF<span className="sr-only"> (opens in a new tab)</span></a> : null}</div></header>{html ? <MarkdownContent html={html} /> : null}</article>;
}
