"use server";
import { revalidatePath } from "next/cache";
import { requireAdmin } from "@/features/auth/session";
import { deleteEducation, moveEducation, saveEducation } from "@/features/education/service";
import { educationFormSchema, educationIdSchema, moveEducationSchema, type EducationActionState } from "@/features/education/validation";
function values(formData: FormData) { return { id: formData.get("id") || undefined, institution: formData.get("institution"), institutionUrl: formData.get("institutionUrl"), degree: formData.get("degree"), field: formData.get("field"), location: formData.get("location"), startDate: formData.get("startDate"), endDate: formData.get("endDate"), isCurrent: formData.get("isCurrent") === "on", descriptionMarkdown: formData.get("descriptionMarkdown") }; }
export async function saveEducationAction(_state: EducationActionState, formData: FormData): Promise<EducationActionState> { await requireAdmin(); const parsed = educationFormSchema.safeParse(values(formData)); if (!parsed.success) return { status: "error", message: "Review the education fields.", fieldErrors: parsed.error.flatten().fieldErrors }; try { await saveEducation(parsed.data); revalidatePath("/admin/education"); revalidatePath("/cv"); return { status: "success", message: parsed.data.id ? "Education saved." : "Education added." }; } catch (error) { console.error("Education save failed.", error instanceof Error ? error.name : "UnknownError"); return { status: "error", message: "The education record could not be saved." }; } }
export async function deleteEducationAction(id: string) { await requireAdmin(); const parsed = educationIdSchema.safeParse(id); if (!parsed.success) return; await deleteEducation(parsed.data); revalidatePath("/admin/education"); revalidatePath("/cv"); }
export async function moveEducationAction(id: string, direction: string) { await requireAdmin(); const parsed = moveEducationSchema.safeParse({ id, direction }); if (!parsed.success) return; await moveEducation(parsed.data.id, parsed.data.direction); revalidatePath("/admin/education"); revalidatePath("/cv"); }
