"use client";

import { ExternalLink } from "lucide-react";
import Link from "next/link";
import { useActionState, useState } from "react";
import { MarkdownEditor } from "@/components/markdown/markdown-editor";
import type { MediaRecord } from "@/features/media/queries";
import { MediaField } from "@/features/media/media-field";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { autosaveProjectAction, renderProjectMarkdownPreviewAction, updateProjectAction } from "@/features/projects/actions";
import type { ProjectTechnologyRecord } from "@/features/projects/queries";
import type { ProjectActionState, ProjectFormInput, ProjectPublicationStatus } from "@/features/projects/validation";
import { FormField } from "@/features/profile/form-field";

interface Props { availableMedia: MediaRecord[]; availableTechnologies: Array<Pick<ProjectTechnologyRecord, "id" | "name" | "slug">>; initialPreviewHtml: string; initialProject: ProjectFormInput; initialStatus: ProjectPublicationStatus }
export function ProjectEditorForm(props: Props) { const [state, action, pending] = useActionState(updateProjectAction, {}); const project = state.savedProject ?? props.initialProject; const status = state.savedStatus ?? props.initialStatus; return <ProjectEditorFields {...props} action={action} key={JSON.stringify({ project, status })} pending={pending} project={project} state={state} status={status} />; }
function ProjectEditorFields({ action, availableMedia, availableTechnologies, initialPreviewHtml, pending, project, state, status }: Omit<Props, "initialProject" | "initialStatus"> & { action: (payload: FormData) => void; pending: boolean; project: ProjectFormInput; state: ProjectActionState; status: ProjectPublicationStatus }) {
  const [markdown, setMarkdown] = useState(project.contentMarkdown); const selected = new Set(project.technologyIds);
  return <form action={action} className="space-y-6"><input name="id" type="hidden" value={project.id} /><textarea hidden name="contentMarkdown" readOnly value={markdown} />
    {state.message ? <div aria-live="polite" className={state.status === "success" ? "rounded-md border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800" : "rounded-md border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800"}>{state.message}</div> : null}
    <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div><span className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-500">CMS status</span><p className="mt-1 font-semibold capitalize text-slate-900">{status}</p></div><Link className="inline-flex items-center gap-2 text-sm font-semibold text-teal-800 underline underline-offset-4" href={`/preview/projects/${project.id}`} target="_blank">Preview public layout <ExternalLink className="size-4" /><span className="sr-only"> (opens in a new tab)</span></Link></div>
    <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="font-serif text-xl font-semibold">Project details</h2><div className="mt-5 grid gap-5 sm:grid-cols-2">
      <FormField errors={state.fieldErrors?.title} htmlFor="title" label="Title"><Input defaultValue={project.title} id="title" maxLength={200} name="title" required /></FormField>
      <FormField description="Changing the title does not change this URL." errors={state.fieldErrors?.slug} htmlFor="slug" label="Slug"><Input defaultValue={project.slug} id="slug" maxLength={120} name="slug" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required /></FormField>
      <div className="sm:col-span-2"><FormField errors={state.fieldErrors?.summary} htmlFor="summary" label="Summary"><Textarea defaultValue={project.summary} id="summary" maxLength={700} name="summary" rows={3} /></FormField></div>
      <FormField errors={state.fieldErrors?.projectStatus} htmlFor="projectStatus" label="Project lifecycle"><Select defaultValue={project.projectStatus} id="projectStatus" name="projectStatus"><option value="planned">Planned</option><option value="active">Active</option><option value="completed">Completed</option><option value="archived">Archived</option></Select></FormField>
      <label className="flex items-center gap-2 self-end pb-3 text-sm font-medium text-slate-700"><input className="size-4" defaultChecked={project.isFeatured} name="isFeatured" type="checkbox" /> Featured project</label>
      <FormField errors={state.fieldErrors?.startedOn} htmlFor="startedOn" label="Start date"><Input defaultValue={project.startedOn ?? ""} id="startedOn" name="startedOn" type="date" /></FormField>
      <FormField errors={state.fieldErrors?.endedOn} htmlFor="endedOn" label="End date"><Input defaultValue={project.endedOn ?? ""} id="endedOn" name="endedOn" type="date" /></FormField>
      <div className="sm:col-span-2"><MediaField description="Choose an uploaded image for the project cover." initialId={project.coverMediaId} initialMedia={availableMedia} label="Managed cover image" name="coverMediaId" /></div>
      <div className="sm:col-span-2"><FormField description="Optional fallback for an externally hosted cover." errors={state.fieldErrors?.coverImageUrl} htmlFor="coverImageUrl" label="External cover image URL"><Input defaultValue={project.coverImageUrl ?? ""} id="coverImageUrl" name="coverImageUrl" type="url" /></FormField></div>
    </div></section>
    <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="font-serif text-xl font-semibold">Project links</h2><div className="mt-5 grid gap-5 sm:grid-cols-3"><FormField errors={state.fieldErrors?.githubUrl} htmlFor="githubUrl" label="GitHub URL"><Input defaultValue={project.githubUrl ?? ""} id="githubUrl" name="githubUrl" type="url" /></FormField><FormField errors={state.fieldErrors?.demoUrl} htmlFor="demoUrl" label="Demo URL"><Input defaultValue={project.demoUrl ?? ""} id="demoUrl" name="demoUrl" type="url" /></FormField><FormField errors={state.fieldErrors?.externalUrl} htmlFor="externalUrl" label="External URL"><Input defaultValue={project.externalUrl ?? ""} id="externalUrl" name="externalUrl" type="url" /></FormField></div></section>
    <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-wrap items-baseline justify-between gap-3"><div><h2 className="font-serif text-xl font-semibold">Technologies</h2><p className="mt-1 text-sm text-slate-500">Choose normalized technologies used by this project.</p></div><Link className="text-sm font-semibold text-teal-800 underline underline-offset-4" href="/admin/projects/technologies">Manage technologies</Link></div>{availableTechnologies.length ? <div className="mt-5 flex flex-wrap gap-3">{availableTechnologies.map((technology) => <label className="flex items-center gap-2 rounded-full border border-slate-300 px-3 py-2 text-sm font-medium text-slate-700" key={technology.id}><input className="size-4" defaultChecked={selected.has(technology.id)} name="technologyIds" type="checkbox" value={technology.id} />{technology.name}</label>)}</div> : <p className="mt-5 rounded-md bg-slate-50 px-4 py-3 text-sm text-slate-600">No technologies yet. Create one from Manage technologies.</p>}{state.fieldErrors?.technologyIds?.map((error) => <p className="mt-2 text-sm text-red-700" key={error}>{error}</p>)}</section>
    <div>{state.fieldErrors?.contentMarkdown?.map((error) => <p className="mb-2 text-sm text-red-700" key={error}>{error}</p>)}<MarkdownEditor autosaveAction={autosaveProjectAction} contentId={project.id} initialPreviewHtml={initialPreviewHtml} media={availableMedia} onChange={setMarkdown} previewAction={renderProjectMarkdownPreviewAction} value={markdown} /></div>
    <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="font-serif text-xl font-semibold">Search and sharing</h2><p className="mt-1 text-sm text-slate-500">Optional project-specific overrides. Shared SEO tooling arrives in Milestone 11.</p><div className="mt-5 grid gap-5 sm:grid-cols-2"><FormField errors={state.fieldErrors?.seoTitle} htmlFor="seoTitle" label="SEO title"><Input defaultValue={project.seoTitle ?? ""} id="seoTitle" maxLength={100} name="seoTitle" /></FormField><FormField errors={state.fieldErrors?.seoDescription} htmlFor="seoDescription" label="SEO description"><Input defaultValue={project.seoDescription ?? ""} id="seoDescription" maxLength={300} name="seoDescription" /></FormField><FormField errors={state.fieldErrors?.canonicalUrl} htmlFor="canonicalUrl" label="Canonical URL"><Input defaultValue={project.canonicalUrl ?? ""} id="canonicalUrl" name="canonicalUrl" type="url" /></FormField><MediaField description="Choose an uploaded image for social previews." initialId={project.ogMediaId} initialMedia={availableMedia} label="Managed social image" name="ogMediaId" /><FormField description="Optional fallback for an externally hosted social image." errors={state.fieldErrors?.ogImageUrl} htmlFor="ogImageUrl" label="External social image URL"><Input defaultValue={project.ogImageUrl ?? ""} id="ogImageUrl" name="ogImageUrl" type="url" /></FormField></div></section>
    <div className="flex flex-wrap justify-end gap-3">{status !== "draft" ? <Button className="border border-slate-300 bg-white text-slate-700 shadow-none hover:bg-slate-100" disabled={pending} name="intent" type="submit" value="draft">Move to draft</Button> : null}{status !== "archived" ? <Button className="border border-slate-300 bg-white text-slate-700 shadow-none hover:bg-slate-100" disabled={pending} name="intent" type="submit" value="archive">Archive</Button> : null}<Button className="border border-slate-300 bg-white text-slate-700 shadow-none hover:bg-slate-100" disabled={pending} name="intent" type="submit" value="save">Save changes</Button>{status !== "published" ? <Button disabled={pending} name="intent" type="submit" value="publish">Publish</Button> : null}</div>
  </form>;
}
