"use client";
import { useActionState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { createTechnologyAction, deleteTechnologyAction, updateTechnologyAction } from "@/features/projects/actions";
import type { TechnologyRecord } from "@/features/projects/queries";
import { FormField } from "@/features/profile/form-field";
export function CreateTechnologyForm() { const [state, action, pending] = useActionState(createTechnologyAction, {}); return <form action={action} aria-label="Create technology" className="space-y-5 rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6">{state.message ? <p aria-live="polite" className={state.status === "success" ? "text-sm text-emerald-700" : "text-sm text-red-700"}>{state.message}</p> : null}<div className="grid gap-5 sm:grid-cols-2"><FormField errors={state.fieldErrors?.name} htmlFor="new-technology-name" label="Name"><Input defaultValue={state.values?.name} id="new-technology-name" maxLength={80} name="name" required /></FormField><FormField description="Leave blank to generate it from the name." errors={state.fieldErrors?.slug} htmlFor="new-technology-slug" label="Slug"><Input defaultValue={state.values?.slug} id="new-technology-slug" maxLength={80} name="slug" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" /></FormField></div><div className="flex justify-end"><Button disabled={pending} type="submit">{pending ? "Creating..." : "Create technology"}</Button></div></form>; }
export function TechnologyEditor({ technology }: { technology: TechnologyRecord }) { const [state, action, pending] = useActionState(updateTechnologyAction, {}); const deleteAction = deleteTechnologyAction.bind(null, technology.id); return <form action={action} aria-label={`Edit ${technology.name}`} className="grid gap-4 border-b border-slate-200 p-5 last:border-b-0 sm:grid-cols-[1fr_1fr_auto] sm:items-end"><input name="id" type="hidden" value={technology.id} /><FormField errors={state.fieldErrors?.name} htmlFor={`technology-name-${technology.id}`} label="Name"><Input defaultValue={technology.name} id={`technology-name-${technology.id}`} maxLength={80} name="name" required /></FormField><FormField errors={state.fieldErrors?.slug} htmlFor={`technology-slug-${technology.id}`} label="Slug"><Input defaultValue={technology.slug} id={`technology-slug-${technology.id}`} maxLength={80} name="slug" required /></FormField><div className="flex gap-2"><Button disabled={pending} type="submit">Save</Button><Button className="bg-red-700 hover:bg-red-600" formAction={deleteAction} onClick={(event) => { if (!window.confirm(`Delete technology "${technology.name}"? It will be removed from ${technology.projectCount} project(s).`)) event.preventDefault(); }} type="submit">Delete</Button></div>{state.message ? <p aria-live="polite" className={state.status === "success" ? "text-sm text-emerald-700 sm:col-span-3" : "text-sm text-red-700 sm:col-span-3"}>{state.message}</p> : null}<p className="text-xs text-slate-500 sm:col-span-3">Used by {technology.projectCount} {technology.projectCount === 1 ? "project" : "projects"}.</p></form>; }
