import type { Metadata } from "next";
import Link from "next/link";
import { PublicShell } from "@/components/public/public-shell";
import { getPublicNavigation } from "@/features/navigation/queries";
import { listPublishedProjects } from "@/features/projects/queries";
import { getPublicSiteData } from "@/features/profile/queries";
import { buildMetadata } from "@/features/seo/metadata";
import { getGlobalSeoSettings } from "@/features/seo/queries";
export async function generateMetadata(): Promise<Metadata> { return buildMetadata(await getGlobalSeoSettings(), { canonicalPath: "/projects", title: "Projects", description: "Selected projects and professional work." }); }
function dateLabel(startedOn: string | null, endedOn: string | null, active: boolean) { const format = (value: string) => new Date(`${value}T00:00:00Z`).toLocaleDateString(undefined, { month: "short", year: "numeric", timeZone: "UTC" }); if (!startedOn) return null; return `${format(startedOn)}${endedOn ? ` – ${format(endedOn)}` : active ? " – present" : ""}`; }
export default async function ProjectsPage() { const [navigation, projects, site] = await Promise.all([getPublicNavigation(), listPublishedProjects(), getPublicSiteData()]); return <PublicShell navigation={navigation} site={site}><section><header className="border-b border-slate-200 pb-8"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--public-accent)]">Portfolio</p><h1 className="mt-3 font-serif text-4xl font-semibold tracking-tight text-slate-950 sm:text-5xl">Projects</h1><p className="mt-4 max-w-2xl text-lg leading-8 text-slate-600">Selected research, software, and professional work.</p></header>{projects.length === 0 ? <div className="py-12"><h2 className="font-serif text-2xl font-semibold">No published projects yet</h2><p className="mt-3 text-slate-600">Published projects will appear here.</p></div> : <ol className="divide-y divide-slate-200">{projects.map((project) => <li className="py-8" key={project.id}><article><div className="flex flex-wrap items-center gap-3 text-xs font-semibold uppercase tracking-[0.12em] text-slate-500"><span>{project.projectStatus}</span>{project.isFeatured ? <span className="text-[var(--public-accent)]">Featured</span> : null}{dateLabel(project.startedOn, project.endedOn, project.projectStatus === "active") ? <span>{dateLabel(project.startedOn, project.endedOn, project.projectStatus === "active")}</span> : null}</div><h2 className="mt-2 font-serif text-2xl font-semibold tracking-tight"><Link className="text-slate-950 hover:text-[var(--public-accent)]" href={`/projects/${project.slug}`}>{project.title}</Link></h2>{project.summary ? <p className="mt-3 leading-7 text-slate-600">{project.summary}</p> : null}{project.technologies.length ? <p className="mt-3 text-sm text-slate-500">{project.technologies.map((technology) => technology.name).join(" · ")}</p> : null}</article></li>)}</ol>}</section></PublicShell>; }
