import type { Metadata } from "next";
import Link from "next/link";
import { PublicShell } from "@/components/public/public-shell";
import { getPublicNavigation } from "@/features/navigation/queries";
import { listPublishedPublications } from "@/features/publications/queries";
import { getPublicSiteData } from "@/features/profile/queries";
import { buildMetadata } from "@/features/seo/metadata";
import { getGlobalSeoSettings } from "@/features/seo/queries";
export async function generateMetadata(): Promise<Metadata> { return buildMetadata(await getGlobalSeoSettings(), { canonicalPath: "/publications", title: "Publications", description: "Academic publications and scholarly work." }); }
function year(value: string | null) { return value ? new Date(`${value}T00:00:00Z`).getUTCFullYear() : null; }
export default async function PublicationsPage() { const [navigation, publications, site] = await Promise.all([getPublicNavigation(), listPublishedPublications(), getPublicSiteData()]); return <PublicShell navigation={navigation} site={site}><section><header className="border-b border-slate-200 pb-8"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--public-accent)]">Academic portfolio</p><h1 className="mt-3 font-serif text-4xl font-semibold tracking-tight sm:text-5xl">Publications</h1><p className="mt-4 max-w-2xl text-lg leading-8 text-slate-600">Journal articles, conference papers, reports, and other scholarly work.</p></header>{publications.length === 0 ? <div className="py-12"><h2 className="font-serif text-2xl font-semibold">No published work yet</h2><p className="mt-3 text-slate-600">Published academic work will appear here.</p></div> : <ol className="divide-y divide-slate-200">{publications.map((item) => <li className="py-8" key={item.id}><article><p className="text-xs font-semibold uppercase tracking-[0.12em] text-slate-500">{item.publicationType}{year(item.publicationDate) ? ` · ${year(item.publicationDate)}` : ""}{item.isFeatured ? " · Featured" : ""}</p><h2 className="mt-2 font-serif text-2xl font-semibold"><Link className="hover:text-[var(--public-accent)]" href={`/publications/${item.slug}`}>{item.title}</Link></h2>{item.authors.length ? <p className="mt-2 text-sm text-slate-600">{item.authors.map((author) => author.name).join(", ")}</p> : null}{item.venue ? <p className="mt-2 text-sm italic text-slate-500">{item.venue}</p> : null}{item.abstract ? <p className="mt-3 line-clamp-3 leading-7 text-slate-600">{item.abstract}</p> : null}</article></li>)}</ol>}</section></PublicShell>; }
