"use client";
import { ArrowDown, ArrowUp, Trash2 } from "lucide-react";
import { useActionState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { deleteSkillAction, moveSkillAction, saveSkillAction } from "@/features/skills/actions";
import type { SkillRecord } from "@/features/skills/queries";
import { FormField } from "@/features/profile/form-field";
export function SkillManager({ records }: { records: SkillRecord[] }) { return <div className="space-y-6"><SkillForm />{records.length ? <div className="space-y-3">{records.map((record, index) => <SkillForm index={index} key={record.id} record={record} total={records.length} />)}</div> : <p className="rounded-xl border border-dashed border-slate-300 bg-white p-8 text-center text-slate-600">No skills yet.</p>}</div>; }
function SkillForm({ record, index = 0, total = 0 }: { record?: SkillRecord; index?: number; total?: number }) { const [state, action, pending] = useActionState(saveSkillAction, {}); return <form action={action} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><input name="id" type="hidden" value={record?.id ?? ""} /><div className="grid items-end gap-4 sm:grid-cols-[1fr_1fr_auto_auto]"><FormField errors={state.fieldErrors?.name} htmlFor={`skill-name-${record?.id ?? "new"}`} label="Skill"><Input defaultValue={record?.name} id={`skill-name-${record?.id ?? "new"}`} name="name" required /></FormField><FormField errors={state.fieldErrors?.category} htmlFor={`skill-category-${record?.id ?? "new"}`} label="Category"><Input defaultValue={record?.category} id={`skill-category-${record?.id ?? "new"}`} name="category" required /></FormField><label className="flex min-h-10 items-center gap-2 text-sm font-medium"><input className="size-4" defaultChecked={record?.isVisible ?? true} name="isVisible" type="checkbox" /> Visible</label><div className="flex gap-1"><Button disabled={pending} type="submit">{record ? "Save" : "Add skill"}</Button>{record ? <><Button aria-label="Move skill up" className="bg-transparent px-2 text-slate-700 shadow-none hover:bg-slate-100" disabled={index === 0} formAction={moveSkillAction.bind(null, record.id, "up")} type="submit"><ArrowUp className="size-4" /></Button><Button aria-label="Move skill down" className="bg-transparent px-2 text-slate-700 shadow-none hover:bg-slate-100" disabled={index === total - 1} formAction={moveSkillAction.bind(null, record.id, "down")} type="submit"><ArrowDown className="size-4" /></Button><Button aria-label="Delete skill" className="bg-transparent px-2 text-red-700 shadow-none hover:bg-red-50" formAction={deleteSkillAction.bind(null, record.id)} type="submit"><Trash2 className="size-4" /></Button></> : null}</div></div>{state.message ? <p aria-live="polite" className={`mt-3 text-sm ${state.status === "error" ? "text-red-700" : "text-emerald-700"}`}>{state.message}</p> : null}</form>; }
