import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { listMedia } from "@/features/media/queries";
import { DeletePublicationForm } from "@/features/publications/delete-publication-form";
import { PublicationEditorForm } from "@/features/publications/publication-editor-form";
import { getPublicationById } from "@/features/publications/queries";
import { publicationIdSchema } from "@/features/publications/validation";
import { renderMarkdown } from "@/lib/markdown/render";
export const metadata: Metadata = { title: "Edit publication | PortfolioCMS" };
export default async function EditPublicationPage({ params }: { params: Promise<{ id: string }> }) { const { id } = await params; const parsed = publicationIdSchema.safeParse(id); if (!parsed.success) notFound(); const [publication, media] = await Promise.all([getPublicationById(parsed.data), listMedia()]); if (!publication) notFound(); const contentMarkdown = publication.draftMarkdown ?? publication.contentMarkdown; const initialPreviewHtml = await renderMarkdown(contentMarkdown); const initialPublication = { id: publication.id, title: publication.title, slug: publication.slug, abstract: publication.abstract, contentMarkdown, publicationType: publication.publicationType, venue: publication.venue, publisher: publication.publisher, publicationDate: publication.publicationDate, doi: publication.doi, externalUrl: publication.externalUrl, pdfMediaId: publication.pdfMediaId, authors: publication.authors.map(({ name, profileUrl, isOwner }) => ({ name, profileUrl, isOwner })), isFeatured: publication.isFeatured, seoTitle: publication.seoTitle, seoDescription: publication.seoDescription, canonicalUrl: publication.canonicalUrl, ogMediaId: publication.ogMediaId, ogImageUrl: publication.ogImageUrl }; return <div className="mx-auto max-w-6xl"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[0.14em] text-teal-800">Publications</p><h1 className="mt-2 font-serif text-3xl font-semibold tracking-tight">Edit publication</h1></div><DeletePublicationForm id={publication.id} title={publication.title} /></div><PublicationEditorForm availableMedia={media} initialPreviewHtml={initialPreviewHtml} initialPublication={initialPublication} initialStatus={publication.status} /></div>; }
