"use client";
import { ArrowDown, ArrowUp, Eye, EyeOff } from "lucide-react";
import { useActionState, useState } from "react";
import { Button } from "@/components/ui/button";
import { saveCvConfigurationAction } from "@/features/cv/actions";
import type { CvProjectOption, CvSectionRecord } from "@/features/cv/queries";
import type { CvSectionType } from "@/features/cv/validation";
const labels: Record<CvSectionType, string> = { profile: "Profile", education: "Education", experience: "Experience", projects: "Selected projects", publications: "Publications", skills: "Skills" };
export function CvManager({ initialProjectIds, initialSections, projects }: { initialProjectIds: string[]; initialSections: CvSectionRecord[]; projects: CvProjectOption[] }) {
  const [sections, setSections] = useState(initialSections); const [projectIds, setProjectIds] = useState(initialProjectIds); const [state, action, pending] = useActionState(saveCvConfigurationAction, {});
  function move(index: number, offset: -1 | 1) { const target = index + offset; if (target < 0 || target >= sections.length) return; setSections((current) => { const next = [...current]; [next[index], next[target]] = [next[target], next[index]]; return next; }); }
  function toggleSection(type: CvSectionType) { setSections((current) => current.map((section) => section.sectionType === type ? { ...section, isVisible: !section.isVisible } : section)); }
  function toggleProject(id: string) { setProjectIds((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]); }
  const configuration = JSON.stringify({ sections: sections.map(({ sectionType, isVisible }) => ({ sectionType, isVisible })), projectIds });
  return <form action={action} aria-label="Configure CV" className="space-y-7"><input name="configuration" type="hidden" value={configuration} />
    <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-serif text-xl font-semibold">Sections</h2><p className="mt-1 text-sm text-slate-600">Arrange the public CV and hide sections without deleting their source data.</p><ol className="mt-5 divide-y divide-slate-200 border-y border-slate-200">{sections.map((section, index) => <li className="flex items-center gap-3 py-3" data-visible={section.isVisible} key={section.sectionType}><div className="min-w-0 flex-1"><p className="font-semibold text-slate-900">{labels[section.sectionType]}</p><p className="text-xs text-slate-500">{section.isVisible ? "Visible publicly" : "Hidden publicly"}</p></div><Button aria-label={`Move ${labels[section.sectionType]} up`} className="bg-transparent px-2 text-slate-700 shadow-none hover:bg-slate-100" disabled={index === 0} onClick={() => move(index, -1)} type="button"><ArrowUp className="size-4" /></Button><Button aria-label={`Move ${labels[section.sectionType]} down`} className="bg-transparent px-2 text-slate-700 shadow-none hover:bg-slate-100" disabled={index === sections.length - 1} onClick={() => move(index, 1)} type="button"><ArrowDown className="size-4" /></Button><Button aria-label={`${section.isVisible ? "Hide" : "Show"} ${labels[section.sectionType]}`} className="min-w-24 border border-slate-300 bg-white text-slate-800 shadow-none hover:bg-slate-100" onClick={() => toggleSection(section.sectionType)} type="button">{section.isVisible ? <Eye className="size-4" /> : <EyeOff className="size-4" />}{section.isVisible ? "Visible" : "Hidden"}</Button></li>)}</ol></section>
    <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-serif text-xl font-semibold">Project selection</h2><p className="mt-1 text-sm text-slate-600">Choose published projects for the selected-projects section. Their order follows this list.</p>{projects.length ? <fieldset className="mt-5 grid gap-3 sm:grid-cols-2"><legend className="sr-only">Projects included in CV</legend>{projects.map((project) => <label className="flex items-start gap-3 rounded-lg border border-slate-200 p-4" key={project.id}><input checked={projectIds.includes(project.id)} className="mt-1 size-4" onChange={() => toggleProject(project.id)} type="checkbox" /><span><span className="block font-semibold text-slate-900">{project.title}</span>{project.summary ? <span className="mt-1 block text-sm leading-6 text-slate-600">{project.summary}</span> : null}</span></label>)}</fieldset> : <p className="mt-5 rounded-lg border border-dashed border-slate-300 p-5 text-sm text-slate-600">Publish a project before selecting it for the CV.</p>}</section>
    <div className="flex items-center justify-between gap-4"><p aria-live="polite" className={`text-sm ${state.status === "error" ? "text-red-700" : "text-emerald-700"}`}>{state.message}</p><Button disabled={pending} type="submit">{pending ? "Saving…" : "Save CV"}</Button></div></form>;
}
