import type { ReactNode } from "react";
import Link from "next/link";
import { MarkdownContent } from "@/components/markdown/markdown-content";
import type { CvSectionRecord } from "@/features/cv/queries";
import type { EducationRecord } from "@/features/education/queries";
import type { ExperienceRecord } from "@/features/experience/queries";
import type { PublicSiteData } from "@/features/profile/queries";
import type { ProjectRecord } from "@/features/projects/queries";
import type { PublicationRecord } from "@/features/publications/queries";
import type { SkillRecord } from "@/features/skills/queries";
import { renderMarkdown } from "@/lib/markdown/render";
function formatMonth(value: string | null) { return value ? new Date(`${value}T00:00:00Z`).toLocaleDateString(undefined, { month: "short", year: "numeric", timeZone: "UTC" }) : null; }
function range(start: string | null, end: string | null, current: boolean) { return [formatMonth(start), current ? "Present" : formatMonth(end)].filter(Boolean).join(" – "); }
export async function CvPresentation({ education, experience, projects, publications, sections, site, skills }: { education: EducationRecord[]; experience: ExperienceRecord[]; projects: ProjectRecord[]; publications: PublicationRecord[]; sections: CvSectionRecord[]; site: PublicSiteData; skills: SkillRecord[] }) {
  const educationHtml = new Map(await Promise.all(education.map(async (record) => [record.id, await renderMarkdown(record.descriptionMarkdown)] as const))); const experienceHtml = new Map(await Promise.all(experience.map(async (record) => [record.id, await renderMarkdown(record.descriptionMarkdown)] as const))); const grouped = new Map<string, SkillRecord[]>(); for (const skill of skills.filter((item) => item.isVisible)) grouped.set(skill.category, [...(grouped.get(skill.category) ?? []), skill]);
  return <article className="cv-document text-slate-800">{sections.map((section) => {
    if (section.sectionType === "profile") return <header className="cv-section border-b-2 border-slate-800 pb-5" key={section.id}><h1 className="font-serif text-4xl font-semibold tracking-tight text-slate-950">{site.owner.name}</h1>{site.owner.headline ? <p className="mt-2 text-lg text-slate-700">{site.owner.headline}</p> : null}<p className="mt-3 flex flex-wrap gap-x-4 gap-y-1 text-sm text-slate-600">{site.owner.location ? <span>{site.owner.location}</span> : null}{site.owner.email ? <a className="underline underline-offset-4" href={`mailto:${site.owner.email}`}>{site.owner.email}</a> : null}{site.socialLinks.map((link) => <a className="underline underline-offset-4" href={link.href} key={link.href} rel="noreferrer" target="_blank">{link.label}</a>)}</p>{site.owner.biography ? <p className="mt-4 max-w-3xl leading-7 text-slate-700">{site.owner.biography}</p> : null}</header>;
    if (section.sectionType === "education" && education.length) return <CvSection key={section.id} title="Education">{education.map((record) => <Timeline heading={record.degree} html={educationHtml.get(record.id) ?? ""} key={record.id} meta={[record.field, record.location].filter(Boolean).join(" · ")} organization={record.institution} period={range(record.startDate, record.endDate, record.isCurrent)} url={record.institutionUrl} />)}</CvSection>;
    if (section.sectionType === "experience" && experience.length) return <CvSection key={section.id} title="Experience">{experience.map((record) => <Timeline heading={record.position} html={experienceHtml.get(record.id) ?? ""} key={record.id} meta={record.location} organization={record.organization} period={range(record.startDate, record.endDate, record.isCurrent)} url={record.organizationUrl} />)}</CvSection>;
    if (section.sectionType === "projects" && projects.length) return <CvSection key={section.id} title="Selected Projects"><ul className="space-y-5">{projects.map((project) => <li className="cv-entry" key={project.id}><div className="flex flex-wrap items-baseline justify-between gap-x-4"><h3 className="font-semibold text-slate-950"><Link className="underline decoration-slate-300 underline-offset-4" href={`/projects/${project.slug}`}>{project.title}</Link></h3><span className="text-sm text-slate-500">{range(project.startedOn, project.endedOn, project.projectStatus === "active")}</span></div>{project.summary ? <p className="mt-1.5 leading-6 text-slate-700">{project.summary}</p> : null}{project.technologies.length ? <p className="mt-1.5 text-sm text-slate-500">{project.technologies.map((technology) => technology.name).join(" · ")}</p> : null}</li>)}</ul></CvSection>;
    if (section.sectionType === "publications" && publications.length) return <CvSection key={section.id} title="Publications"><ol className="space-y-5">{publications.map((publication) => <li className="cv-entry" key={publication.id}><h3 className="font-semibold text-slate-950"><Link className="underline decoration-slate-300 underline-offset-4" href={`/publications/${publication.slug}`}>{publication.title}</Link></h3>{publication.authors.length ? <p className="mt-1 text-sm text-slate-700">{publication.authors.map((author) => author.name).join(", ")}</p> : null}<p className="mt-1 text-sm italic text-slate-500">{[publication.venue, publication.publicationDate ? new Date(`${publication.publicationDate}T00:00:00Z`).getUTCFullYear() : null].filter(Boolean).join(" · ")}</p></li>)}</ol></CvSection>;
    if (section.sectionType === "skills" && grouped.size) return <CvSection key={section.id} title="Skills"><dl className="grid gap-x-8 gap-y-3 sm:grid-cols-[9rem_1fr]">{Array.from(grouped).map(([category, records]) => <div className="contents" key={category}><dt className="font-semibold text-slate-950">{category}</dt><dd className="text-slate-700">{records.map((record) => record.name).join(" · ")}</dd></div>)}</dl></CvSection>;
    return null;
  })}</article>;
}
function CvSection({ children, title }: { children: ReactNode; title: string }) { return <section className="cv-section mt-8"><h2 className="mb-4 border-b border-slate-300 pb-2 font-serif text-2xl font-semibold text-slate-950">{title}</h2>{children}</section>; }
function Timeline({ heading, html, meta, organization, period, url }: { heading: string; html: string; meta: string; organization: string; period: string; url: string | null }) { return <article className="cv-entry mb-5"><div className="flex flex-wrap items-baseline justify-between gap-x-4"><div><h3 className="font-semibold text-slate-950">{heading}</h3><p className="text-sm text-slate-700">{url ? <a className="underline decoration-slate-300 underline-offset-4" href={url} rel="noreferrer" target="_blank">{organization}</a> : organization}{meta ? ` · ${meta}` : ""}</p></div>{period ? <p className="text-sm text-slate-500">{period}</p> : null}</div>{html ? <div className="mt-2 text-sm"><MarkdownContent html={html} /></div> : null}</article>; }
